apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kube-dashboard
  namespace: dashboard
spec:
  secretName: my-kube-dashboard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - dashboard.xyz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dashboard.xyz
